version: "3.7"

services:
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
      - 4444:4444
      - 8265:8265
    env_file:
      - ./django/.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true
    links:
      - redis
    shm_size: "2gb"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  ng:
    container_name: ng
    build: ./angular
    ports:
      - "80:80"
    volumes:
      - ./angular/route-optimizer/:/usr/src/app/
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379
  osrm:
    container_name: osrm
    image: whaniewski/osrm-backend-route-optimizer
    ports:
      - 5000:5000
  celery:
    restart: always
    build: ./django
    command: celery -A route_optimizer worker -l debug
    volumes:
      - ./django/:/usr/src/app/
    env_file:
      - ./django/.env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
