version: "3.3"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
      - 4444:4444
      - 8265:8265
    env_file:
      - ./.django-env-dev
    depends_on:
      - db
    stdin_open: true
    tty: true
    links:
      - redis
    shm_size: "2gb"
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.postgres-env
  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379
  osrm:
    container_name: osrm
    image: whaniewski/osrm-backend-route-optimizer
    ports:
      - 5000:5000
  celery:
    restart: always
    build: .
    command: celery -A route_optimizer worker -l debug
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.django-env-dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
