version: "3.7"

services:
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
      - 4444:4444
    env_file:
      - ./django/.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true
    links:
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  ng:
    container_name: ng
    build: ./angular
    ports:
      - "80:80"
    volumes:
      - ./angular/route-optimizer/:/usr/src/app/
    environment:
      - NODE_ENV=dev
      - CHOKIDAR_USEPOLLING=true
  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379
  #osrm:
  #build:
  #context: ./OSRM
  #args:
  #- PBF=http://download.geofabrik.de/europe/poland/podlaskie-latest.osm.pbf
  #- STXXL_SIZE=200000
  #ports:
  #- 5000:5000
  #volumes:
  #- /run/media/wojciech/66509E74509E4AA7/OSRM/:.

volumes:
  postgres_data:
