# Generated by Django 2.2.6 on 2019-12-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191212_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='business_trips', to='data.Profile', verbose_name='przypisany'),
        ),
    ]
