# Generated by Django 2.2.6 on 2020-02-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200225_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='route_version',
            field=models.IntegerField(default=0, verbose_name='Wersja'),
        ),
    ]
