# Generated by Django 2.2.6 on 2020-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200306_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='task_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
