# Generated by Django 2.2.6 on 2020-05-16 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0014_auto_20200508_1732'),
        ('data', '0014_route_route_type'),
    ]

    operations = [
    ]
