# Generated by Django 2.2.6 on 2020-05-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0017_auto_20200517_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['pk'], 'verbose_name': 'filia firmy', 'verbose_name_plural': 'filie firmy'},
        ),
        migrations.AlterModelOptions(
            name='requistion',
            options={'ordering': ['created_by', '-pk'], 'verbose_name': 'zapotrzebowanie',
                     'verbose_name_plural': 'zapotrzebowania'},
        ),
        migrations.RemoveField(
            model_name='businesstrip',
            name='vertices_number',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='business_trips', to='data.Department',
                                    verbose_name='Punkt startowy i końcowy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='task_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
