# Generated by Django 2.2.6 on 2020-05-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0018_auto_20200521_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_point',
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='end_point_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_point_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
