# Generated by Django 2.2.6 on 2020-05-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0019_auto_20200523_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_profit', models.FloatField(verbose_name='oszacowany zysk')),
                ('assignment_date', models.DateTimeField(auto_now=True, verbose_name='data przypisania')),
                ('business_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='requisitions', to='data.BusinessTrip',
                                                    verbose_name='delegacja')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions',
                                              to='data.Company', verbose_name='firma')),
                ('created_by',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='created_requisitions', to=settings.AUTH_USER_MODEL,
                                   verbose_name='stworzony przez')),
            ],
            options={
                'verbose_name': 'zapotrzebowanie',
                'verbose_name_plural': 'zapotrzebowania',
                'ordering': ['created_by', '-pk'],
            },
        ),
        migrations.DeleteModel(
            name='Requistion',
        ),
    ]
