# Generated by Django 2.2.6 on 2020-06-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20200524_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstrip',
            options={'ordering': ['pk'], 'verbose_name': 'delegacja', 'verbose_name_plural': 'delegacje'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['pk'], 'verbose_name': 'firma', 'verbose_name_plural': 'firmy'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['pk'], 'verbose_name': 'hotel', 'verbose_name_plural': 'hotele'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['pk']},
        ),
    ]
