# Generated by Django 2.2.6 on 2019-12-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='data rozpoczęcia')),
                ('finish_date', models.DateTimeField(verbose_name='data zakończenia')),
            ],
            options={
                'verbose_name': 'delegacja',
                'verbose_name_plural': 'delegacje',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Company')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotele',
            },
            bases=('data.company',),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'firma', 'verbose_name_plural': 'firmy'},
        ),
        migrations.AlterField(
            model_name='company',
            name='nip',
            field=models.CharField(max_length=11, unique=True, verbose_name='nip'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postcode',
            field=models.CharField(max_length=8, verbose_name='kod pocztowy'),
        ),
        migrations.CreateModel(
            name='Requistion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_profit', models.FloatField(verbose_name='oszacowany zysk')),
                ('assignment_date', models.DateTimeField(auto_now=True, verbose_name='data przypisania')),
                ('business_trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requistions', to='data.BusinessTrip', verbose_name='delegacja')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requistions', to='data.Company', verbose_name='firma')),
            ],
            options={
                'verbose_name': 'zapotrzebowanie',
                'verbose_name_plural': 'zapotrzebowania',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil użytkownika',
                'verbose_name_plural': 'profile użytkownika',
            },
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trips', to='data.Profile', verbose_name='przypisany'),
        ),
    ]
