# Generated by Django 2.2.6 on 2019-12-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191206_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': [
                'pk'], 'verbose_name': 'firma', 'verbose_name_plural': 'firmy'},
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('segment_order', models.IntegerField()),
                ('day', models.IntegerField()),
                ('business_trip', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='data.BusinessTrip')),
                ('end_point', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Company')),
                ('start_point', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.Company')),
            ],
        ),
    ]
