# Generated by Django 2.2.6 on 2019-12-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191215_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='route_version',
            field=models.IntegerField(default=1, verbose_name='Wersja'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_version',
            field=models.IntegerField(default=1, verbose_name='Wersja'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(
                blank=True, max_length=60, verbose_name='ulica'),
        ),
    ]
