# Generated by Django 2.2.6 on 2019-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191226_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='distance_constraint',
            field=models.IntegerField(default=50, verbose_name='Maksymalny limit kilometrów jednego dnia'),
            preserve_default=False,
        ),
    ]
