# Generated by Django 2.2.6 on 2020-02-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200121_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requistion',
            name='business_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requistions', to='data.BusinessTrip', verbose_name='delegacja'),
        ),
        migrations.AlterField(
            model_name='requistion',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requistions', to='data.Profile', verbose_name='stworzony przez'),
        ),
    ]
