# Generated by Django 2.2.6 on 2020-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200214_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'firma', 'verbose_name_plural': 'firmy'},
        ),
        migrations.AlterModelOptions(
            name='requistion',
            options={'ordering': ['-pk'], 'verbose_name': 'zapotrzebowanie', 'verbose_name_plural': 'zapotrzebowania'},
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='przetworzona'),
        ),
    ]
