# Generated by Django 2.2.6 on 2020-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200227_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='route_version',
            field=models.IntegerField(default=1, verbose_name='Wersja'),
        ),
    ]
