# Generated by Django 2.2.6 on 2020-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200506_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('START', 'Początek trasy'), ('VISIT', 'Odwiedzenie firmy'), ('FINISH_AT_DEPOT', 'Koniec podtrasy w filii'), ('FINISH_AT_HOTEL', 'Koniec podtrasy w hotelu'), ('START_FROM_DEPOT', 'Początek podtrasy w filii'), ('START_FROM_HOTEL', 'Początek podtrasy w hotelu'), ('FINISH', 'Koniec trasy')], default='VISIT', max_length=20),
        ),
    ]
